// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Rmarken5/file-broadcaster/observer (interfaces: Observer)

// Package observer is a generated GoMock package.
package observer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// GetIdentifier mocks base method.
func (m *MockObserver) GetIdentifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdentifier indicates an expected call of GetIdentifier.
func (mr *MockObserverMockRecorder) GetIdentifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentifier", reflect.TypeOf((*MockObserver)(nil).GetIdentifier))
}

// OnUpdate mocks base method.
func (m *MockObserver) OnUpdate(arg0 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUpdate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnUpdate indicates an expected call of OnUpdate.
func (mr *MockObserverMockRecorder) OnUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUpdate", reflect.TypeOf((*MockObserver)(nil).OnUpdate), arg0)
}
